### ISSUE TITLE
If you specify a 'done' method option, subsequent configured tasks will not execute

### ISSUE THREAD

**Issue by SimplGy** [gruntjs/grunt-contrib-requirejs#37]
Looks like using the 'done' option blocks any tasks which would follow it. Here's the scene:

```
grunt.task.run [ 'copy:js', 'requirejs', 'clean:unoptimizedFiles' ] # clean:unoptimizedFiles Won't run right after requirejs for some reason.
```

It does not run that clean step, and there is no output referring to that step, even in verbose mode. If I run the step separately, it is successful.

When I comment out the `done` option, however, tasks following requirejs work again.

```
requirejs:
  oneForAll:
    options:
      ...
      optimize: "none"
#          done: (done, output) -> # commenting this out fixes it
#            duplicates = require('rjs-build-analysis').duplicates(output)
#            if duplicates.length > 0
#              grunt.log.subhead 'Duplicates found in requirejs build:'
#              grunt.log.warn duplicates
#              done new Error 'r.js built duplicate modules'
#            done()
```
