### ISSUE TITLE
Build script does not run main script

### ISSUE THREAD

**Issue by binarykitchen** [gruntjs/grunt-contrib-requirejs#39]
I have another gotcha: With the following configuration in my Gruntfile.coffee I am unable to run the main script in the browser:

```
    requirejs:
      compile:
        options:
          baseUrl: "client/scripts/compiled"
          name: 'main'
          mainConfigFile: "client/scripts/compiled/config/require.config.js"
          out: "server/public/j/main.js"
          useStrict: true
          optimize: 'none'
          preserveLicenseComments: false
```

`server/public/j/main.js` has all the source code but does not run anything. At the bottom I see this line which makes no sense:

```
define("main", function(){});
```

Any clues?
